version: '3.8'
networks:
  payment:
services:
  payment-service:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5004:5004
    networks:
      - payment
    volumes:
      - ./src/log:/usr/src/app/src/log
    restart: unless-stopped
  promtail:
    image: grafana/promtail
    volumes:
      - ./src/log:/var/payment
      - ./promtail:/etc/promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - payment
